"""Derivation-level lagged TC certificate-frontier scheduler.

This module implements the paper's derivation-level scheduler as a standalone
runtime next to the older bounded MPL prefix harness.

The core distinction is derivation-level legality: a value can be generated by
one allowed derivation while another derivation to the same value is forbidden.
The scheduler records both facts without treating a forbidden derivation as a
forbidden value.
"""
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping


def _word_value(word: tuple[int, ...]) -> int:
    value = 1
    for factor in word:
        value *= factor
    return value


def _normalize_word(*words: tuple[int, ...]) -> tuple[int, ...]:
    merged: list[int] = []
    for word in words:
        merged.extend(word)
    return tuple(sorted(merged))


def _sort_derivations(
    derivations: set["DerivationCertificate"],
) -> tuple["DerivationCertificate", ...]:
    return tuple(
        sorted(
            derivations,
            key=lambda d: (
                d.recursion_index,
                d.left_factor,
                d.right_factor,
                d.value,
                d.allowed,
                d.reason,
            ),
        )
    )


@dataclass(frozen=True)
class DerivationCertificate:
    """One derivation attempt inside a recursion."""

    left_factor: int
    right_factor: int
    value: int
    canonical_word: tuple[int, ...]
    recursion_index: int
    allowed: bool
    reason: str = ""

    @property
    def alias(self) -> tuple[int, int]:
        return tuple(sorted((self.left_factor, self.right_factor)))


@dataclass(frozen=True)
class ValueCertificate:
    """Canonical odd-composite value certificate."""

    value: int
    canonical_word: tuple[int, ...]
    allowed_derivations: tuple[DerivationCertificate, ...]
    forbidden_derivations: tuple[DerivationCertificate, ...]
    created_at_recursion: int
    active_from_recursion: int
    aliases: tuple[tuple[int, int], ...]

    def with_derivations(
        self,
        *,
        allowed: set[DerivationCertificate] | None = None,
        forbidden: set[DerivationCertificate] | None = None,
    ) -> "ValueCertificate":
        allowed_set = set(self.allowed_derivations)
        forbidden_set = set(self.forbidden_derivations)
        if allowed is not None:
            allowed_set.update(allowed)
        if forbidden is not None:
            forbidden_set.update(forbidden)
        aliases = {derivation.alias for derivation in allowed_set}
        return ValueCertificate(
            value=self.value,
            canonical_word=self.canonical_word,
            allowed_derivations=_sort_derivations(allowed_set),
            forbidden_derivations=_sort_derivations(forbidden_set),
            created_at_recursion=self.created_at_recursion,
            active_from_recursion=self.active_from_recursion,
            aliases=tuple(sorted(aliases)),
        )


CompositeCertificate = ValueCertificate


@dataclass(frozen=True)
class RecursionTrace:
    """Inspectable record for one derivation-level recursion."""

    recursion_index: int
    emitted_prime: int
    active_multipliers_before: tuple[int, ...]
    known_targets_before: tuple[int, ...]
    generated_values: tuple[int, ...]
    generated_certificates: tuple[ValueCertificate, ...]
    allowed_derivations: tuple[DerivationCertificate, ...]
    forbidden_derivations: tuple[DerivationCertificate, ...]
    forbidden_values: tuple[int, ...]
    delayed_obstruction_horizon: int | None
    certified_prime_buffer: tuple[int, ...]
    not_certified_due_to_obstruction: tuple[int, ...]
    active_for_next_recursion: tuple[int, ...]
    frontier_markers: tuple[int, ...]
    activation_cohort: tuple[int, ...]
    notes: tuple[str, ...]

    @property
    def generated_composites(self) -> tuple[int, ...]:
        return self.generated_values

    @property
    def active_primes_before(self) -> tuple[int, ...]:
        return self.active_multipliers_before

    @property
    def active_composites_before(self) -> tuple[int, ...]:
        return tuple(value for value in self.known_targets_before if value not in self.active_multipliers_before)

    @property
    def forbidden_products(self) -> tuple[str, ...]:
        return tuple(
            f"{d.left_factor}*{d.right_factor}={d.value} {d.reason}"
            for d in self.forbidden_derivations
        )

    @property
    def active_primes_after(self) -> tuple[int, ...]:
        return self.active_for_next_recursion


@dataclass(frozen=True)
class SchedulerState:
    """Public snapshot of the scheduler state."""

    recursion_index: int
    emitted_primes: tuple[int, ...]
    certified_primes: tuple[int, ...]
    active_multipliers: tuple[int, ...]
    known_targets: tuple[int, ...]
    pending_prime_buffer: tuple[int, ...]
    certification_frontier: int
    composite_certificates: Mapping[int, ValueCertificate]
    activation_cohorts: Mapping[int, tuple[int, ...]]

    @property
    def active_primes(self) -> tuple[int, ...]:
        return self.active_multipliers

    @property
    def active_composite_certificates(self) -> tuple[ValueCertificate, ...]:
        return tuple(self.composite_certificates.values())


class LaggedCertificateFrontierScheduler:
    """Unbounded derivation-level lagged certificate-frontier scheduler."""

    def __init__(self) -> None:
        self._next_recursion_index = 2
        self._emitted_primes: list[int] = [2, 3]
        self._emitted_odd: set[int] = {3}
        self._certified_primes: set[int] = {3}
        self._certified_at: dict[int, int] = {3: 1}
        self._pending_prime_buffer: list[int] = [5]
        self._certification_frontier = 5
        self._certificates: dict[int, ValueCertificate] = {}
        self._forbidden_by_value: dict[int, set[DerivationCertificate]] = {}
        self._activation_cohorts: dict[int, set[int]] = {2: {3}}
        self._traces: list[RecursionTrace] = []

    def step(self) -> RecursionTrace:
        """Run the next recursion and return its trace."""

        recursion_index = self._next_recursion_index
        emitted_prime = self._pop_next_prime()

        active_multipliers = tuple(sorted(self._emitted_odd))
        known_target_words = self._known_target_words(emitted_prime)
        known_targets = tuple(sorted(known_target_words))
        derivation_value_limit = emitted_prime * emitted_prime * 3

        allowed_by_value, allowed_derivations = self._generate_allowed_derivations(
            recursion_index=recursion_index,
            active_multipliers=active_multipliers,
            known_target_words=known_target_words,
            value_limit=derivation_value_limit,
        )

        existing_values = set(self._certificates)
        self._merge_allowed_certificates(recursion_index, allowed_by_value)
        generated_values = tuple(sorted(value for value in allowed_by_value if value not in existing_values))

        forbidden_derivations = self._record_forbidden_derivations(
            recursion_index=recursion_index,
            emitted_prime=emitted_prime,
            active_multipliers=active_multipliers,
            generated_values=generated_values,
        )
        self._attach_forbidden_derivations(forbidden_derivations)

        generated_set = set(allowed_by_value) | existing_values
        forbidden_values = tuple(
            sorted({derivation.value for derivation in forbidden_derivations if derivation.value not in generated_set})
        )
        delayed_obstruction_horizon = forbidden_values[0] if forbidden_values else None

        frontier_markers = self._frontier_markers(delayed_obstruction_horizon)
        new_frontier = frontier_markers[-1] if frontier_markers else self._certification_frontier
        certified_buffer = self._certify_free_boundaries(new_frontier)
        withheld = self._withheld_boundaries(new_frontier, delayed_obstruction_horizon)

        self._emitted_primes.append(emitted_prime)
        self._emitted_odd.add(emitted_prime)
        self._certified_primes.add(emitted_prime)
        self._certified_at.setdefault(emitted_prime, recursion_index)
        for prime in certified_buffer:
            self._certified_primes.add(prime)
            self._certified_at[prime] = recursion_index

        activation_recursion = recursion_index + 1
        cohort = self._activation_cohorts.setdefault(activation_recursion, set())
        cohort.add(emitted_prime)
        cohort.update(certified_buffer)

        self._certification_frontier = new_frontier
        self._pending_prime_buffer.extend(certified_buffer)
        self._pending_prime_buffer = sorted(
            prime
            for prime in set(self._pending_prime_buffer)
            if prime not in self._emitted_odd
        )

        generated_certificates = tuple(self._certificates[value] for value in generated_values)
        trace = RecursionTrace(
            recursion_index=recursion_index,
            emitted_prime=emitted_prime,
            active_multipliers_before=active_multipliers,
            known_targets_before=known_targets,
            generated_values=generated_values,
            generated_certificates=generated_certificates,
            allowed_derivations=tuple(
                sorted(
                    allowed_derivations,
                    key=lambda d: (d.left_factor, d.right_factor, d.value),
                )
            ),
            forbidden_derivations=_sort_derivations(forbidden_derivations),
            forbidden_values=forbidden_values,
            delayed_obstruction_horizon=delayed_obstruction_horizon,
            certified_prime_buffer=tuple(certified_buffer),
            not_certified_due_to_obstruction=tuple(withheld),
            active_for_next_recursion=tuple(sorted(self._emitted_odd)),
            frontier_markers=frontier_markers,
            activation_cohort=tuple(sorted(cohort)),
            notes=(
                "current emitted axis is target only",
                "new objects activate after recursion close",
                f"derivation_value_limit={derivation_value_limit}",
            ),
        )
        self._traces.append(trace)
        self._next_recursion_index += 1
        return trace

    def run_recursions(self, count: int) -> tuple[RecursionTrace, ...]:
        """Run ``count`` recursions and return their traces."""

        if count < 0:
            raise ValueError("count must be non-negative")
        return tuple(self.step() for _ in range(count))

    def generate_primes(self, count: int) -> list[int]:
        """Return the first ``count`` emitted primes."""

        return self.generate_prime_prefix(count)

    def generate_prime_prefix(self, count: int) -> list[int]:
        """Return the first ``count`` emitted primes, extending the stream."""

        if count < 0:
            raise ValueError("count must be non-negative")
        while len(self._emitted_primes) < count:
            self.step()
        return self._emitted_primes[:count]

    def current_state(self) -> SchedulerState:
        """Return an immutable public snapshot."""

        certificates = {
            value: self._certificates[value]
            for value in sorted(self._certificates)
        }
        cohorts = {
            recursion: tuple(sorted(values))
            for recursion, values in sorted(self._activation_cohorts.items())
        }
        next_known = self._known_target_words(
            self._pending_prime_buffer[0] if self._pending_prime_buffer else 0
        )
        return SchedulerState(
            recursion_index=self._next_recursion_index,
            emitted_primes=tuple(self._emitted_primes),
            certified_primes=tuple(sorted(self._certified_primes)),
            active_multipliers=tuple(sorted(self._emitted_odd)),
            known_targets=tuple(sorted(next_known)),
            pending_prime_buffer=tuple(self._pending_prime_buffer),
            certification_frontier=self._certification_frontier,
            composite_certificates=MappingProxyType(certificates),
            activation_cohorts=MappingProxyType(cohorts),
        )

    def trace(self) -> tuple[RecursionTrace, ...]:
        """Return traces for completed recursions."""

        return tuple(self._traces)

    def _pop_next_prime(self) -> int:
        if not self._pending_prime_buffer:
            raise RuntimeError("prime buffer is empty")
        emitted = self._pending_prime_buffer.pop(0)
        if emitted in self._emitted_odd:
            raise RuntimeError("prime buffer contained an already emitted odd axis")
        return emitted

    def _known_target_words(self, emitted_prime: int) -> dict[int, tuple[int, ...]]:
        targets = {prime: (prime,) for prime in self._certified_primes}
        for value, certificate in self._certificates.items():
            targets[value] = certificate.canonical_word
        if emitted_prime:
            targets[emitted_prime] = (emitted_prime,)
        return targets

    def _generate_allowed_derivations(
        self,
        *,
        recursion_index: int,
        active_multipliers: tuple[int, ...],
        known_target_words: dict[int, tuple[int, ...]],
        value_limit: int,
    ) -> tuple[dict[int, set[DerivationCertificate]], set[DerivationCertificate]]:
        by_value: dict[int, set[DerivationCertificate]] = {}
        all_derivations: set[DerivationCertificate] = set()
        for left in active_multipliers:
            left_word = (left,)
            for right, right_word in known_target_words.items():
                word = _normalize_word(left_word, right_word)
                value = _word_value(word)
                if value > value_limit:
                    continue
                derivation = DerivationCertificate(
                    left_factor=left,
                    right_factor=right,
                    value=value,
                    canonical_word=word,
                    recursion_index=recursion_index,
                    allowed=True,
                )
                by_value.setdefault(value, set()).add(derivation)
                all_derivations.add(derivation)
        return by_value, all_derivations

    def _merge_allowed_certificates(
        self,
        recursion_index: int,
        allowed_by_value: dict[int, set[DerivationCertificate]],
    ) -> None:
        for value, derivations in allowed_by_value.items():
            word = min((d.canonical_word for d in derivations), key=lambda w: (len(w), w))
            if value in self._certificates:
                self._certificates[value] = self._certificates[value].with_derivations(
                    allowed=set(derivations),
                )
                continue

            certificate = ValueCertificate(
                value=value,
                canonical_word=word,
                allowed_derivations=_sort_derivations(set(derivations)),
                forbidden_derivations=_sort_derivations(self._forbidden_by_value.get(value, set())),
                created_at_recursion=recursion_index,
                active_from_recursion=recursion_index + 1,
                aliases=tuple(sorted(d.alias for d in derivations)),
            )
            self._certificates[value] = certificate

    def _record_forbidden_derivations(
        self,
        *,
        recursion_index: int,
        emitted_prime: int,
        active_multipliers: tuple[int, ...],
        generated_values: tuple[int, ...],
    ) -> set[DerivationCertificate]:
        forbidden: set[DerivationCertificate] = set()
        self_product_word = (emitted_prime, emitted_prime)
        forbidden.add(
            DerivationCertificate(
                left_factor=emitted_prime,
                right_factor=emitted_prime,
                value=emitted_prime * emitted_prime,
                canonical_word=self_product_word,
                recursion_index=recursion_index,
                allowed=False,
                reason="current self-product delayed",
            )
        )

        audit_multipliers = tuple(sorted(set(active_multipliers) | {emitted_prime}))
        audit_limit = max((emitted_prime * emitted_prime) * 3, max(generated_values, default=0) * 2)
        for left in audit_multipliers:
            for right in generated_values:
                word = _normalize_word((left,), self._certificates[right].canonical_word)
                value = _word_value(word)
                if value >= audit_limit:
                    continue
                if left == emitted_prime:
                    reason = "current axis is not active multiplier"
                else:
                    reason = "target created in current recursion"
                forbidden.add(
                    DerivationCertificate(
                        left_factor=left,
                        right_factor=right,
                        value=value,
                        canonical_word=word,
                        recursion_index=recursion_index,
                        allowed=False,
                        reason=reason,
                    )
                )

        for derivation in forbidden:
            self._forbidden_by_value.setdefault(derivation.value, set()).add(derivation)
        return forbidden

    def _attach_forbidden_derivations(
        self,
        forbidden_derivations: set[DerivationCertificate],
    ) -> None:
        grouped: dict[int, set[DerivationCertificate]] = {}
        for derivation in forbidden_derivations:
            if derivation.value in self._certificates:
                grouped.setdefault(derivation.value, set()).add(derivation)

        for value, derivations in grouped.items():
            self._certificates[value] = self._certificates[value].with_derivations(
                forbidden=derivations,
            )

    def _frontier_markers(self, delayed_obstruction_horizon: int | None) -> tuple[int, ...]:
        return tuple(
            value
            for value in sorted(self._certificates)
            if self._certification_frontier < value
            and (delayed_obstruction_horizon is None or value < delayed_obstruction_horizon)
        )

    def _certify_free_boundaries(self, new_frontier: int) -> list[int]:
        if new_frontier <= self._certification_frontier:
            return []
        covered = set(self._certificates)
        certified: list[int] = []
        value = self._certification_frontier + 2
        while value < new_frontier:
            if value not in covered:
                certified.append(value)
            value += 2
        return certified

    def _withheld_boundaries(
        self,
        new_frontier: int,
        delayed_obstruction_horizon: int | None,
    ) -> list[int]:
        if delayed_obstruction_horizon is None:
            return []
        higher_markers = [value for value in sorted(self._certificates) if value > new_frontier]
        if not higher_markers:
            return []
        upper = higher_markers[0]
        covered = set(self._certificates)
        withheld: list[int] = []
        value = new_frontier + 2
        while value < upper:
            if value != delayed_obstruction_horizon and value not in covered:
                withheld.append(value)
            value += 2
        return withheld
